global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Мониторинг самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  # Пример добавления сервиса для мониторинга
  - job_name: 'example-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'java:8080' ]